In [2]:
# !pip install numpy

#### Defining an array

In [14]:
import numpy as np

arr= np.array([[1,2,3], [4,5,6],[22,33,44], [33,21,11]])

print("-"*20)
print(arr)
print("The shape of an array is : ", arr.shape)
print("The dimension of array: ", arr.ndim)
print("Total items in ana array", arr.size)
print("Item size of array", arr.itemsize)

--------------------
[[ 1  2  3]
 [ 4  5  6]
 [22 33 44]
 [33 21 11]]
The shape of an array is :  (4, 3)
The dimension of array:  2
Total items in ana array 12
Item size of array 8


In [12]:
arr= np.array([[[1,2,3], [4,5,6]],[[22,33,44], [33,21,11]]])
print("-"*20)
print(arr)
print("The shape of an array is : ", arr.shape)
print("The dimension of array: ", arr.ndim)
print("Total items in ana array", arr.size)
print("Item size of array", arr.itemsize)

--------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[22 33 44]
  [33 21 11]]]
The shape of an array is :  (2, 2, 3)
The dimension of array:  3
Total items in ana array 12
Item size of array 8


In [13]:
arr= np.array([[[1,2,3], [4,5,6]],[[22,33,44], [33,21,11]], [[22,33,44], [33,21,11]]])
print("-"*20)
print(arr)
print("The shape of an array is : ", arr.shape)
print("The dimension of array: ", arr.ndim)
print("Total items in ana array", arr.size)
print("Item size of array", arr.itemsize)

--------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[22 33 44]
  [33 21 11]]

 [[22 33 44]
  [33 21 11]]]
The shape of an array is :  (3, 2, 3)
The dimension of array:  3
Total items in ana array 18
Item size of array 8


In [15]:
arr= np.array([[[1,2,3], [4,5,6], [33,54,66]],[[22,33,44], [33,21,11]], [[22,33,44], [33,21,11]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [16]:
arr= np.array([[[1,2,3], [4,5,6], [33,54,66]],[[22,33,44], [33,21,11],[99,93,91]], [[22,33,44], [33,21,11]]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [17]:
arr= np.array([[[1,2,3], [4,5,6], [33,54,66]],[[22,33,44], [33,21,11],[99,93,91]], [[22,33,44], [33,21,11], [88,86,84]]])


In [18]:
# Defining an array
import numpy as np


# list1= [12,34,45,56,78]
# 1d array
narray= np.array([12,34,45,56,78])

In [6]:
narray

array([12, 34, 45, 56, 78])

In [7]:
narray.shape

(5,)

In [8]:
narray.ndim

1

In [10]:
narray[2]

np.int64(45)

In [19]:
# higher dimensional array
# 2d array
a=np.array([[1,2,3,4,5], [6,5,4,3,2],[22,34,5,6,8]])
a.shape

(3, 5)

In [20]:
a.ndim

2

In [14]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  5,  4,  3,  2],
       [22, 34,  5,  6,  8]])

In [21]:
### dimension of an array is referrred to as "axis"

# dimension of an array
#  dimension of data that is represented by the array

threed_array= np.array([[[1,2], [3,4]],
                        [[1,22], [33,99]]])

In [24]:
threed_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 1, 22],
        [33, 99]]])

In [25]:
threed_array.shape

(2, 2, 2)

In [28]:
threed_array[0]

array([[1, 2],
       [3, 4]])

In [29]:
threed_array[1]

array([[ 1, 22],
       [33, 99]])

In [30]:
threed_array[1][0]

array([ 1, 22])

In [31]:
threed_array[0][1]

array([3, 4])

##### Difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3:

In [36]:
# Attributes of an array::  ndim, shape, size, dtype
threed_array.ndim
print(threed_array.shape) # is a tuple of non negative integer that specify the number of elements along each dimension
print(threed_array.size)
print(threed_array.dtype)

(2, 2, 2)
8
int64


In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [44]:
np.empty(3) # intializes an array with random values or depends on the state of memory

array([2.25893737e-315, 0.00000000e+000, 0.00000000e+000])

In [45]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np

In [53]:
# print(np.array([1,2,3]))
print(np.array([[1,2,3], [4,5,6]]))

[[1 2 3]
 [4 5 6]]


In [8]:
new= np.array([[1,2,3,4], [4,5,6,4], [7,8,9,4], [10,11,12,4]])

In [9]:
new

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  4],
       [ 7,  8,  9,  4],
       [10, 11, 12,  4]])

In [10]:
print(new.shape)
print(new.ndim)
print(new.size)

(4, 4)
2
16


In [11]:
ex1= np.array([[1,2,3], 
          [4,5,6]])
ex1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ex1.ndim

2

In [ ]:
# ex= np.array([[[[1,2,3], [4,5,6]], [[11,22,3], [4,5,6]], [[11,22,3], [42,52,64]]]])
ex= np.array([[[[1,2,3], 
          [4,5,6]]]])
print(ex.ndim)

3


In [1]:
# ex[0][0][0][2]